### ISSUE TITLE
double joining chat

### ISSUE THREAD

**Issue by rakslice** [alamminsalo/orion#145]
When opening a channel for the first time after launch, Orion attempts to join the channel twice (displaying two "Joined channel #foo" notifications).

**Comment by rakslice** [comment]
This appeared in master between cb913e4adba5ae96ba0d0678ec36b5043e4d2a79 (fail) and
356cc55a178f42248fbbf8720e1092d575aa7535 (pass)

**Comment by ahjolinna** [comment]
@rakslice : has there been any major change in login as now when I tried to login, orion opened my browser (firefox) instead of having the whole thing inside orion...
also after I logged-in and "accepted orion" it didnt work at first...aka it failed to connect to localhost*...
but with the 2nd try it worked just fine..

*it was : http://localhost:8979/?access_token=<hidden>&scope=user_read+user_subscriptions+user_follows_edit+chat_login

**Comment by rakslice** [comment]
@ahjolinna That's part of an earlier change,  https://github.com/alamminsalo/orion/commit/f37b2e6a0eb902fc8acaaa0f59099ee1a148623d . If you can reproduce that connection problem please open a separate ticket for it.

**Comment by rakslice** [comment]
The reason the v5 API change triggered this problem is that the `kraken/base` URL `NetworkManager::testConnection()` was requesting is not supported in the newer API and getting a network error. As a quick fix I changed it to do a different request https://github.com/alamminsalo/orion/pull/146

However it's not clear to me why these errors resulted in the double join; there is possibly still an issue in the case of an actual network failure.

**Comment by rakslice** [comment]
I tested with the network is offline at launch and with the network going offline and online again while playing, and in both scenarios I did not reproduce a double-join afterward in the same Orion session. I'll close this for now.

**Comment by ahjolinna** [comment]
This seems to fix my login issue also, good work
