### ISSUE TITLE
Help wanted testing / feedback for upcoming 1.6 branch

### ISSUE THREAD

**Issue by alamminsalo** [alamminsalo/orion#183]
There's now a upcoming `material-design` (ver 1.6) branch available, some suggestions/feedback/regression testing would be welcome now

Features:
- New and fresh material UI !
- Merged search and featured into one view
- Huge refactoring of codebase to a more sane direction (qml singletons, splitted some behaviour which wasn't in right classes, **settings has it's own class**, and more)
- Chatview font size can now be changed via ctrl + scrolling
- Moving from QuickControls 1.x to 2.x
- Icon theme moved to Material Icons
- Chat panel is now global and resizable (in locked mode)

I think the most critical part is to check some distros and see if they break the app. I have a feeling some components used (StackLayout most probably) breaks on older qt libs

**Comment by ahjolinna** [comment]
first thing I notice was that when u click on some channel its hard to see at times the icons and text: 

![image](https://user-images.githubusercontent.com/6993072/27408251-68929d0c-56e4-11e7-8443-f03eeeeccddb.png)


btw. there is the KDE's [Kirigami](https://techbase.kde.org/Kirigami) project that is made for mobile but will also works/scale on desktop..I think it would scale better on both compare to material-design that is made for android/mobile 

Kirigami(2.x) only depends on "qt5-quickcontrols2" so its not KDE only thing

currently KDE uses at least Kirigami on discover and kalgebra on desktop, and kde-connect for android version.

**Comment by ahjolinna** [comment]
the chat is also little bit broken: 
![image](https://user-images.githubusercontent.com/6993072/27412029-9a179394-56fa-11e7-90d8-fcd9031d98bb.png)

**Comment by alamminsalo** [comment]
I see the KDE somehow prevents the actual theme from loading, the screenshots don't look right at all

**Comment by ahjolinna** [comment]
Good to know, as I was wondering why it looked so different/worse

Anyway I would still check Kirigami out as it seems to have more scalability...at least if you want to make both desktop and mobile version

**Comment by alamminsalo** [comment]
Here's some screenshots how it should look like, they are visible on the branch readme

[1](https://user-images.githubusercontent.com/5585454/27404242-031e59a6-56d6-11e7-8956-a9d63dcc6034.png)

[2](https://user-images.githubusercontent.com/5585454/27404330-47ba6708-56d6-11e7-96d5-1283224a17dc.png)

[3](https://user-images.githubusercontent.com/5585454/27404337-541ead74-56d6-11e7-91f4-ce3803a458a2.png)

**Comment by ahjolinna** [comment]
this how settings look like: 
![image](https://user-images.githubusercontent.com/6993072/27433783-c685efa2-575e-11e7-8098-b0738a5a0073.png)

it seems orion wont/cant load the background, : 
`<Unknown File>: QML Material: Binding loop detected for property "background"`

----------

@alamminsalo : Anyway, did u have time to check [Kirigami](https://techbase.kde.org/Kirigami) at least on [android](https://play.google.com/store/apps/details?id=org.kde.kirigamigallery), if so what do you think about it?

github link: https://github.com/KDE/kirigami
announcement: https://dot.kde.org/2016/03/30/kde-proudly-presents-kirigami-ui

it seems [Subsurface mobile version](https://subsurface-divelog.org/2016/03/announcing-subsurface-mobile-for-android/) will also use it (the Linus Torvalds diving app)

**Comment by alamminsalo** [comment]
I just fixed the bug (via overriding QT_QUICK_CONTROLS_STYLE, a temporary solution really), now it should look ok...

The floating-player-mode is also currently under works

Chat: Yep, I think the chat could have a pin button, which makes it behave as in earlier version.

About kirigami: I haven't yet, but I will  :)

**Comment by ahjolinna** [comment]
@alamminsalo : yeah that worked, I hope that you will fix that chat thing or either go with Kirigami2.x

I'm glad that KDE made kirigami as more of an quickcontrols2  extension than a "KDE only" thing, so it shouldn't bring problems to none KDE users.

**Comment by rakslice** [comment]
I did a quick test build of this in Windows with the released Qt 5.9.0 build.

- The stream function buttons that appear in the lower right when you select a stream are not immediately obvious. Could they have text labels? Could the button for watching live at least be just FA `play` rather than `play-circle`? People recognise their old friend https://www.iso.org/obp/ui#iec:grs:60417:5107B very quickly :D
- As mentioned, there needs to be a mode where both the entire video area and chat are visible on screen :D
- IMO, if anything should pop in over-top of the video instead of pushing it out of the way, it's the top and bottom toolbars; they currently cause the video area to resize when they pop in which is jarring.
- The grid layouts are a bit awkward:
![image](https://user-images.githubusercontent.com/1845104/27467339-8f204d18-5796-11e7-8bbc-175b83358960.png)
  Images shown in the grid are being overly cropped -- game box art often has titles at the top & bottom that are being cropped out -- while most of the window space is being used for the grey background.
![image](https://user-images.githubusercontent.com/1845104/27467314-5039fafe-5796-11e7-9e13-1b8a9c08d391.png)
  The VOD thumbnails are being letterboxed within in an area that is partially covered by the text box; with typical stream title sizes, only half the thumbnail that can be seen
- There's a bit of error in the positioning of the grid "offline" shade boxes and text boxes at some window sizes: they're off by a pixel on the top and/or right leaving a bright single line of the image showing
![image](https://user-images.githubusercontent.com/1845104/27467626-ce8497b4-5798-11e7-9005-fdad1dd17012.png)
I can easily see these while resizing the window, and they come up consistently at the window sizes they happen at.

**Comment by alamminsalo** [comment]
Thanks for feedback, the issues mentioned should be pretty easy to fix. 

I forgot to tell that the AwesomeIcons have been replaced by Material icons, to go with the design. I'll update it to the start comment

**Comment by ahjolinna** [comment]
I just notice that if you change the font to for example to [Source Sans Pro](http://adobe-fonts.github.io/source-sans-pro/) it resets back to "Arabic Newspaper" when you close/restart the app

**Comment by wenolu** [comment]
My main issue with orion is still the font of the chat, it looks really bad and being unable to remove the left column with stuff to have a 16:9 video

Otherwise, this is my only way to watch streams on my turboshit pentium e machine so god bless you

**Comment by alamminsalo** [comment]
Left column has been removed in the upcoming release (moved to top, not visible in fullscreenmode)
Chat font will be also changed

**Comment by alamminsalo** [comment]
Fixes so far:
- chat is now pinnable (lock icon), alters layout so chat is always visible
- labels added to channel popup drawer buttons
- adjustments to gridviews so less space goes to waste

**Comment by ahjolinna** [comment]
@alamminsalo : have you thought about making/adding a light theme option? for those who don't like the dark theme for some reason or another.

-----------

I hate to sound like I'm "quibbling" about this, but have you tried the Kirigami thing, and if you did, what do u think about it.

I think this version is fine for desktop at least, but if you are going for mobile version also then maybe you need some more/better scalability, I think this is what Kirigami could bring to the table...at least more easily

and Kirigami is not a KDE only thing, like KDE projects have been before in KDE 4 time period...the team learned from that mistake at least

-------------

I also notice that there are some new [clazy](https://github.com/KDE/clazy) warnings, I would recommend that someone would look into, before releasing a stable version.

**Comment by ahjolinna** [comment]
I just notice a small thing missing, the volume icon...its looks little bit weird to just see the volume slider

**Comment by alamminsalo** [comment]
@ahjolinna the material theme supports light theme and that would be trivial to implement as setting.
Kirigami would need another branch for prototyping, I haven't had yet the time to sit down for this. Wouldn't adding kirigami add yet another dependency?

**Comment by ahjolinna** [comment]
Yes you would need Kirigami as a dependencies (which is just dependent on quickcontrols, as it's works just as an extension of it)

**Comment by WyohKnott** [comment]
Some feedback on the normal branch (I've used v1.5.1rc extensively, with qtmultimedia engine on Fedora 25):
 
 - ~~Why is the chat on the left now?~~ I've just seen the checkbox in the option.
 - Why does the button Toggle Floating Player do nothing? What is it supposed to do?

(Compiling material-design branch, commit 0e71823 right now, still Fedora 25 + qtmultimedia):

```“orion” terminated by signal SIGSEGV (Address boundary error)```

**Comment by AndyShade** [comment]
Need adjustable notifications size or and (for me)  they must appear much closer to desktop border and trey panel.

**Comment by alamminsalo** [comment]
@WyohKnott The floating player button enables player to "float" over other views (for example search view) when enabled

**Comment by AreFinstad** [comment]
missing timecodes for vods aswell as previews when for the timeline for the vods.

also think we need a way to mark vods as watched manually or automatically when watched.

**Comment by ahjolinna** [comment]
I only now noticed that the mouse/cursor auto-hide doesn't work anymore

**Comment by alamminsalo** [comment]
Here's some progress today: 
- fixed player mouse autohide being clumsy
- dark/light option
- chat at bottom (possibly only on android and mobile devices)
![orion](https://user-images.githubusercontent.com/5585454/27519845-8807f0d2-5a05-11e7-8321-2dd48a27ec1f.png)

@ahjolinna the font selector option was added as feature to check how different fonts would look with the UI, I didn't intent it would be a visible feature when released

**Comment by ahjolinna** [comment]
Well that explains it, I personally would like to have that option to choose your font

**Comment by AreFinstad** [comment]
do think the player needs a bit more hotkeys. like mousewheel to adjust volume and click to pause vod for example.  the new ui does look really great so far though!

**Comment by ahjolinna** [comment]
@AreFinstad : check #134 and give your own suggestion for some hotkeys possibilities

**Comment by ahjolinna** [comment]
@alamminsalo : I was thinking if you would also do an experimental Kirigami version, and then release a "stable" version that would include all 3 UI's and let people to build their version and give feedback on all 3 version and see which is fits better and then make it default on the next one.

but then again if you see something in kirigami that would make it out of the question..then thats fine.
btw. Kirigami 1.x is based on quickcontrols1 and 2.x is based quickcontrols2.x (the Kirigami 2.2 just arrived few days ago)
check [the Kirigami2 API overview](https://api.kde.org/kirigami/html/index.html)

-----

I did just notice that with light theme doesn't make the player UI "light", and the top-bar's font color is too "bright/light"...otherwise the material UI seems to work now

----

also what is the minimum Qt5 version for the material UI? (any idea)

**Comment by alamminsalo** [comment]
@ahjolinna I need to test building with older versions to see if anything breaks. Ubuntu has qt 5.6 currently IIRC, so I think targeting this version would be wisest

**Comment by ahjolinna** [comment]
@alamminsalo : well at least on openSUSE leap 42.2 (Qt5.6 based) doesn't have libqt5-qtquickcontrols2..by default at least

**Comment by ahjolinna** [comment]
@alamminsalo : is there a reason why "right mouse clicking" the stream/video area pauses the stream, if this is a mobile thing that's fine but at least on desktop its little bit annoying if you miss click or try to move the app somewhere (another monitor) etc.

also if you have the "chat on bottom" option enabled and watch in fullscreen and try to open chat it won't open and the bottom player UI vanishes....it does work on windowed mode just fine

**Comment by ahjolinna** [comment]
I don't know if this is attentional or not but if you have the chat locked and then try hide it...it looks like this:
![image](https://user-images.githubusercontent.com/6993072/27618074-e076fb8c-5bc2-11e7-8439-284cf664c8cc.png)

**Comment by ahjolinna** [comment]
and about light mode, it seems the chat shows dark font against dark background for the "channel subscription" notifications:
![image](https://user-images.githubusercontent.com/6993072/27618658-4dbac4dc-5bc6-11e7-974a-1005e5e89228.png)

also shouldn't the player UI also change to light, it looks little bit off when everything else has changed but that:
![image](https://user-images.githubusercontent.com/6993072/27618736-baa1a5d4-5bc6-11e7-9311-5f44521efa5f.png)

**Comment by ahjolinna** [comment]
I just notice one irritating thing when watching VOD's, at times if I try to press the play/pause button it sometimes registers that on the "seekbar" instead so that means the stream will go back to the beginning, has this something to do with the mobile side stuff? where "click/touch area" is bigger

**Comment by ahjolinna** [comment]
more..again... :D 
if I scroll the channel list at least on my "followed" on windowed mode it start to "twitch", sometimes more at time less

**Comment by alamminsalo** [comment]
Todays fixes have arrived:

* more polished switching between themes (including player view headers)
* added channel logo to channel drawer, added sunken effect to text for easier readability there
* heightened player headers a bit; to combat issues with misclicking seekbar. Now contains more space between the elements
* animations to player headers
* android tweaks to controls around the application
* fixes to chat (fixed also the dark system message background)

After bit of testing, I'm planning on merging to master soon. The usability is already above 1.5 version IMO. 

I fear minimum Qt version will be 5.8. This is because current UI needs Controls 2.1, which was added in Qt 5.8. We'll need AppImage or Flatpak because of this, to distribute folks over Ubuntu and others

**Comment by ahjolinna** [comment]
@alamminsalo : currently choosing between snap, flatpak & appimage...can be little bit pain in the ass... as snap is only used by ubuntu and appimage is on favored by rpm based distros (fedora & openSUSE)....flatpak seems the most neutral as many do seem support it also (as main one or 2nd optional one).

It seems Gnome and KDE ("app store") are both currently supporting flatpak but there is difference with the 2nd one... Gnome went with appimage and KDE with snap (if I do remember correctly)...we have to see if they will support all 3 somedays

[Steam apparently (offically?) went with flatpak](https://www.phoronix.com/scan.php?page=news_item&px=Flatpak-Steam-Flathub).
so it seems that flatpak is the most favorable from many sides

but I wonder how good the flatpak/snap/appimage support are on these distros that are using Qt5.7 or older. So why not release the current master branch as 1.5.2 as the last Qt5.6 compatible version...and then release 1.6 for those distros that can use Qt5.8+ and maybe an "experimental flatpak (or some other)" release for those who want.

**Comment by probonopd** [comment]
AppImage can definitely do what you are looking for, and it is the most distribtion-agnostic of the three.

If you can get this to build on Travis CI for Linux, then we can convert it to an AppImage easily using https://github.com/probonopd/linuxdeployqt.

**Comment by ahjolinna** [comment]
all 3 are more or less as distribution-agnostic as the other, the question is just which one has wider/mainstream support and flatpak seems to gain more ground on this. 

"And generally the latest Flatpak version was available on all of the latest distribution releases...Where Snap was only using the latest version in Ubuntu 17.04 Zesty and Debian Stretch. Snap support in Ubuntu was out-of-date, Fedora doesn't have the support in the main repository on F25, the Gentoo Snaps were outdated, the openSUSE support was outdated, and on Mageia the support wasn't even available."  -- [from phoronix](https://www.phoronix.com/scan.php?page=news_item&px=Snaps-v-Flatpaks-Linux-Distros)

personally I really don't know how AppImage is support outside of the rpm based distros (I mean offically)...for example arch and more importantly Ubuntu. I don't say that there are any technical reason why AppImage it self wont wont on those distro but what is those distros support that format...as the support has to be a two way street to work properly.

and as KDE has went with flatpak first and snap 2nd...and gnome supports Flatpak also..I think gnome did go with AppImage as the 2nd option...but I could be wrong, if I am wrong and Gnome supports snap instead of AppImage that means the 2 major DE's don't support AppImage at all.

because of this I can't really give my vote for AppImage, good maybe as it is..not enough support.
plus why I see those "support" so important? because that will make the mainstream/enduser life easier and that is what I think it should be about...those who care about these technical stuff can already create their own version if they want or use that "unofficial spinoff" version

**Comment by probonopd** [comment]
Sorry but I think you are entierly confusing things, maybe you are mixing up AppImage with Snappy?

So, in an nutshell,
* _Flatpak_ comes from the GNOME camp and is made by Red Hat employees. It needs to be supported by/installed in the distribution
* _Snappy_ comes from Canonical and is preinstalled mainly on Ubuntu. It needs to be supported by/installed in the distribution
* _AppImage_ is a true community effort not related to any particular distribution or company. It _does not need any kind of support from the distribution_, and nothing (besides a working FUSE installation) needs to be installed in the distribution. It works by loop-mounting a filesystem image and executing whatever is contained inside, very similar to how things work in macOS

[DistroWatch concluded](https://distrowatch.com/weekly.php?issue=20160704) that out of the three systems, it was the only one that worked reliably everywhere.

As for adoption, the [list of upstream-provided AppImages](https://github.com/AppImage/AppImageKit/wiki/AppImages) exceeds the list of Flatpaks manyfold.

**Comment by alamminsalo** [comment]
Thanks for input, I've recently merged this
