### ISSUE TITLE
no audio in 1.6.6(-git)

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#251]
for some reason I don't get any audio anymore with orion on openSUSE (tumblweed)....I use my [own repo](https://build.opensuse.org/package/show/home:ahjolinna/orion) version not the "offical" one.

everything else works as it should, so it I don't think it's a problem with my system...I think

gdb doesn't give any errors

**Comment by mrgreywater** [comment]
Probs this https://github.com/alamminsalo/orion/commit/9fb2e6b3c15a6aab89798f8f91b7cbf53b12d853#diff-dae2dd70920f587d6de8c05d302f468eR100

I moved it from here https://github.com/alamminsalo/orion/commit/9fb2e6b3c15a6aab89798f8f91b7cbf53b12d853#diff-48e50e9fdd3b57abc0ec993a28b8ced4L590 where it previously never worked, because Qt.platform === "linux" will never be true. (It's Qt.platform.os === "linux")

**Comment by ahjolinna** [comment]
yeah that fixed it

**Comment by mrgreywater** [comment]
Should be fixed with #252

**Comment by mrgreywater** [comment]
can you close this issue if there are no more problems?
