### ISSUE TITLE
orion crashes on chakraOS and wont build on opensuse

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#98]
so I just builded orion on chakraOS and it seems to crash when I star/open a stream, here is gdb log: 
[orion-log](https://github.com/alamminsalo/orion/files/924415/orion.txt) , chakraOS uses Qt5.8

and when I try to build orion for [openSUSE on obs](https://build.opensuse.org/package/show/home:ahjolinna/orion), it fails to build on both leap 42.2 and tumbleweed (rolling)

here is leap 42.2 build log: [link](https://paste.kde.org/pksqkmk1v/mpvawk/raw)
tumbleweed build log: [link](https://paste.kde.org/p1ur0srd1/eccvxv/raw)

-----

Latest commit was 20e051d

**Comment by ahjolinna** [comment]
okay now it seems to work on chakraOS...after I did strace debugging....or MAYBE because I removed a folder from my "home folder" called GPUCache that is created by orion...and has filles called:
"data_0"  "data_1"  "data_2"  "data_3"  "index"

anyway here is the strace log if you care: [orion-strace.txt](https://github.com/alamminsalo/orion/files/924423/orion-strace.txt)

**Comment by XenonPK** [comment]
The build on openSUSE is successful, however, the build service checks the compiler output for common errors and invalidates the package if any are found.

The problem seems to be with functions that have a bunch of if statements to determine what to return, but return nothing if all the checks fail, which ends up being the value of a random memory address.

Should be easy to fix... @rakslice ? @alamminsalo  ? I am unsure what the logic behind the if statements or how the returns are used so I don't want to potentially break it.

**Comment by ahjolinna** [comment]
@XenonPK : I really didn't check the build log...
anyhow I hope "GPUCache" folder thing  also could be fixed

**Comment by ahjolinna** [comment]
when that patch has been merged I can close this and make a new separate bug report about the "GPUCache" folder issue

**Comment by rakslice** [comment]
If you have a core file from that crash it would be good to hang onto and maybe grab a backtrace in gdb for it at some point :)
